// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsFx-aCGXHwZYemeC2r633ICgJg9A3aRI',
    appId: '1:441782521828:android:3ebe6ccab1f71d108781f1',
    messagingSenderId: '441782521828',
    projectId: 'bookingmanager-f3d8e',
    databaseURL: 'https://bookingmanager-f3d8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookingmanager-f3d8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEnUEVnIosg5TZxA5lGa9oWx26LQZd0PI',
    appId: '1:441782521828:ios:c48bb7c261b7ca678781f1',
    messagingSenderId: '441782521828',
    projectId: 'bookingmanager-f3d8e',
    databaseURL: 'https://bookingmanager-f3d8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookingmanager-f3d8e.appspot.com',
    iosClientId: '441782521828-clt0opn7v3dv9cu199mdhc1rdm1p5db8.apps.googleusercontent.com',
    iosBundleId: 'ertugrulcakici.bookingManager',
  );
}
